name: Fotografias_service

on:
  workflow_call:
env: 
    App_name: 'Fotografias.API'
    Dotnet_Version: '10'

jobs: 
  build: 
    runs-on: ubuntu-latest 
    env: 
      TipoEjecucion: 'Validacion de variables'

    steps: 
      - name: Mostrar Variables Todas
        env:
          mensaje: Hola soy una variable
        run : |
          echo "Aplicacion: $App_name"
          echo "Version de framework: $Dotnet_Version"
          echo "Variable local: $TipoEjecucion"
          echo $mensaje
        
      - name: Usar Variable
        run: echo $framework

      - name: Variables del repositorio
        run: echo ${{vars.PROYECT_DESCRIPTION}}

      - name: Reemplazar appsettings
        shell: pwsh
        run: |
          $json = Get-Content "appsettings.json" | ConvertFrom-Json
          
          $json.ConnectionStrings.default = "Prueba del cambio exitosa"

          $json | ConvertTo-Json -Depth 10 | Set-Content appsettings.json
          echo $json