name: Fotografias_service

on:
  push:
    branches:
      - features/variables-en-yml
  pull_request:
    branches:
      - develop
env: 
    App_name: 'Fotografias.API'
    Dotnet_Version: '10'

jobs: 
  build: 
    runs-on: ubuntu-latest 
    env: 
      TipoEjecucion: 'Validacion de variables'

    steps: 
      - name: Mostrar Variables Todas
        env:
          mensaje: Hola soy una variable
        run : |
          echo "Aplicacion: $App_name"
          echo "Version de framework: $Dotnet_Version"
          echo "Variable local: $TipoEjecucion"
          echo $mensaje
          echo "Mostrar rama de liberacion: ${{github.ref}}"
      
      - name: Crear Variable
        run: echo "framework= NET.10" >> ${{github.ref}}
        
      - name: Usar Variable
        run: echo $framework

      - name: Revision de código 
        uses: actions/checkout@v4 
      
      - name: Setup .NET 
        uses: actions/setup-dotnet@v4 
        with: 
          dotnet-version: '10.0.x'

      - name: Restaurar dependencias
        run: dotnet restore ./Fotografias.Api.sln
        
      - name: Compilar proyecto
        run: dotnet build ./Fotografias.Api.sln --configuration Release --no-restore
        
      #- name: Ejecutar pruebas con cobertura de código
      #  run: dotnet test ./Fotografias.Api.Test/Fotografias.Api.Test.csproj --collect:"XPlat Code Coverage"